name: zaifa
description: ZAIFA - Voice-powered AI assistant frontend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  speech_to_text: ^7.0.0
  google_fonts: ^6.2.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  modern_launcher_name: ^1.0.0

flutter:
  uses-material-design: true

modern_launcher_name:
  name: "ZAIFA"
